# Config file 

pva_chan: "aspn/vectorNav/positionvelocityattitude"
imu_chan: "aspn/vectorNav/rawimu"
gps_chan: "aspn/vectorNav/geodeticposition3d"

imu_dt: 0.01
imu2platform: [1, 0, 0, 0, 1, 0, 0, 0, 1]
accel_sigma: [0.05, 0.05, 0.05]
gyro_sigma: [0.005, 0.005, 0.005]
accel_tau: 500
gyro_tau: 500
accel_bias_initial_sigma: 5e-3
accel_bias_steady_state_sigma: 5e-3
gyro_bias_initial_sigma: 5e-5
gyro_bias_steady_state_sigma: 5e-5

pva_dt: 0.2

gps_leverarm: [0, 0, 0]